//export const server = "https://vochaafunding.web.app"
export const server = "http://localhost:5000"
export const auth_path = "/auth"
export const getname_path = "/getname"
export const createcontest_path = "/createcontest"
export const gettasks_path = "/gettasks"
export const updatepullrequests_path = "/updatepullrequests"